export const MAVLINK_V2_STX = 0xfd
export const MAVLINK_V2_HEADER_LENGTH = 10
export const MAVLINK_V2_CHECKSUM_LENGTH = 2
export const MAVLINK_V2_SIGNATURE_LENGTH = 13
export const MAVLINK_V2_INCOMPAT_FLAG_SIGNED = 0x01

export const MAVLINK_MESSAGE_IDS = {
  HEARTBEAT: 0,
  SYS_STATUS: 1,
  OPTICAL_FLOW: 100,
  CAN_FRAME: 386,
  CANFD_FRAME: 387,
  GLOBAL_POSITION_INT: 33,
  PARAM_REQUEST_LIST: 21,
  PARAM_VALUE: 22,
  PARAM_SET: 23,
  ATTITUDE: 30,
  RC_CHANNELS: 65,
  FILE_TRANSFER_PROTOCOL: 110,
  COMMAND_ACK: 77,
  COMMAND_LONG: 76,
  AUTOPILOT_VERSION: 148,
  STATUSTEXT: 253,
  LOG_REQUEST_LIST: 117,
  LOG_ENTRY: 118,
  LOG_REQUEST_DATA: 119,
  LOG_DATA: 120,
  LOG_REQUEST_END: 122,
  MAG_CAL_PROGRESS: 191,
  MAG_CAL_REPORT: 192,
  UAVCAN_NODE_STATUS: 310,
  UAVCAN_NODE_INFO: 311,
  SETUP_SIGNING: 256
} as const

export const MAVLINK_MESSAGE_CRCS: Record<number, number> = {
  [MAVLINK_MESSAGE_IDS.HEARTBEAT]: 50,
  [MAVLINK_MESSAGE_IDS.SYS_STATUS]: 124,
  [MAVLINK_MESSAGE_IDS.OPTICAL_FLOW]: 175,
  [MAVLINK_MESSAGE_IDS.CAN_FRAME]: 132,
  [MAVLINK_MESSAGE_IDS.CANFD_FRAME]: 4,
  [MAVLINK_MESSAGE_IDS.GLOBAL_POSITION_INT]: 104,
  [MAVLINK_MESSAGE_IDS.PARAM_REQUEST_LIST]: 159,
  [MAVLINK_MESSAGE_IDS.PARAM_VALUE]: 220,
  [MAVLINK_MESSAGE_IDS.PARAM_SET]: 168,
  [MAVLINK_MESSAGE_IDS.ATTITUDE]: 39,
  [MAVLINK_MESSAGE_IDS.RC_CHANNELS]: 118,
  [MAVLINK_MESSAGE_IDS.FILE_TRANSFER_PROTOCOL]: 84,
  [MAVLINK_MESSAGE_IDS.COMMAND_ACK]: 143,
  [MAVLINK_MESSAGE_IDS.COMMAND_LONG]: 152,
  [MAVLINK_MESSAGE_IDS.AUTOPILOT_VERSION]: 178,
  [MAVLINK_MESSAGE_IDS.STATUSTEXT]: 83,
  [MAVLINK_MESSAGE_IDS.LOG_REQUEST_LIST]: 128,
  [MAVLINK_MESSAGE_IDS.LOG_ENTRY]: 56,
  [MAVLINK_MESSAGE_IDS.LOG_REQUEST_DATA]: 116,
  [MAVLINK_MESSAGE_IDS.LOG_DATA]: 134,
  [MAVLINK_MESSAGE_IDS.LOG_REQUEST_END]: 203,
  [MAVLINK_MESSAGE_IDS.MAG_CAL_PROGRESS]: 92,
  [MAVLINK_MESSAGE_IDS.MAG_CAL_REPORT]: 36,
  [MAVLINK_MESSAGE_IDS.UAVCAN_NODE_STATUS]: 28,
  [MAVLINK_MESSAGE_IDS.UAVCAN_NODE_INFO]: 95,
  // crc_extra from the MAVLink common dialect (c_library_v2
  // mavlink_msg_setup_signing.h: MAVLINK_MSG_ID_SETUP_SIGNING_CRC 71).
  [MAVLINK_MESSAGE_IDS.SETUP_SIGNING]: 71
}

export const MAVLINK_PAYLOAD_LENGTHS: Record<number, number> = {
  [MAVLINK_MESSAGE_IDS.HEARTBEAT]: 9,
  [MAVLINK_MESSAGE_IDS.SYS_STATUS]: 43,
  [MAVLINK_MESSAGE_IDS.OPTICAL_FLOW]: 34,
  [MAVLINK_MESSAGE_IDS.CAN_FRAME]: 16,
  [MAVLINK_MESSAGE_IDS.CANFD_FRAME]: 72,
  [MAVLINK_MESSAGE_IDS.GLOBAL_POSITION_INT]: 28,
  [MAVLINK_MESSAGE_IDS.PARAM_REQUEST_LIST]: 2,
  [MAVLINK_MESSAGE_IDS.PARAM_VALUE]: 25,
  [MAVLINK_MESSAGE_IDS.PARAM_SET]: 23,
  [MAVLINK_MESSAGE_IDS.ATTITUDE]: 28,
  [MAVLINK_MESSAGE_IDS.RC_CHANNELS]: 42,
  [MAVLINK_MESSAGE_IDS.FILE_TRANSFER_PROTOCOL]: 254,
  [MAVLINK_MESSAGE_IDS.COMMAND_ACK]: 10,
  [MAVLINK_MESSAGE_IDS.COMMAND_LONG]: 33,
  [MAVLINK_MESSAGE_IDS.AUTOPILOT_VERSION]: 78,
  [MAVLINK_MESSAGE_IDS.STATUSTEXT]: 54,
  [MAVLINK_MESSAGE_IDS.LOG_REQUEST_LIST]: 6,
  [MAVLINK_MESSAGE_IDS.LOG_ENTRY]: 14,
  [MAVLINK_MESSAGE_IDS.LOG_REQUEST_DATA]: 12,
  [MAVLINK_MESSAGE_IDS.LOG_DATA]: 97,
  [MAVLINK_MESSAGE_IDS.LOG_REQUEST_END]: 2,
  [MAVLINK_MESSAGE_IDS.MAG_CAL_PROGRESS]: 27,
  [MAVLINK_MESSAGE_IDS.MAG_CAL_REPORT]: 54,
  [MAVLINK_MESSAGE_IDS.UAVCAN_NODE_STATUS]: 17,
  [MAVLINK_MESSAGE_IDS.UAVCAN_NODE_INFO]: 116,
  // initial_timestamp(8) + target_system(1) + target_component(1) + secret_key(32)
  [MAVLINK_MESSAGE_IDS.SETUP_SIGNING]: 42
}

export const MAVLINK_MIN_PAYLOAD_LENGTHS: Record<number, number> = {
  [MAVLINK_MESSAGE_IDS.HEARTBEAT]: 9,
  [MAVLINK_MESSAGE_IDS.SYS_STATUS]: 31,
  [MAVLINK_MESSAGE_IDS.OPTICAL_FLOW]: 26,
  [MAVLINK_MESSAGE_IDS.CAN_FRAME]: 16,
  [MAVLINK_MESSAGE_IDS.CANFD_FRAME]: 72,
  [MAVLINK_MESSAGE_IDS.GLOBAL_POSITION_INT]: 28,
  [MAVLINK_MESSAGE_IDS.PARAM_REQUEST_LIST]: 2,
  [MAVLINK_MESSAGE_IDS.PARAM_VALUE]: 25,
  [MAVLINK_MESSAGE_IDS.PARAM_SET]: 23,
  [MAVLINK_MESSAGE_IDS.ATTITUDE]: 28,
  [MAVLINK_MESSAGE_IDS.RC_CHANNELS]: 42,
  [MAVLINK_MESSAGE_IDS.FILE_TRANSFER_PROTOCOL]: 254,
  [MAVLINK_MESSAGE_IDS.COMMAND_ACK]: 3,
  [MAVLINK_MESSAGE_IDS.COMMAND_LONG]: 33,
  [MAVLINK_MESSAGE_IDS.AUTOPILOT_VERSION]: 60,
  [MAVLINK_MESSAGE_IDS.STATUSTEXT]: 51,
  [MAVLINK_MESSAGE_IDS.LOG_REQUEST_LIST]: 6,
  [MAVLINK_MESSAGE_IDS.LOG_ENTRY]: 14,
  [MAVLINK_MESSAGE_IDS.LOG_REQUEST_DATA]: 12,
  [MAVLINK_MESSAGE_IDS.LOG_DATA]: 97,
  [MAVLINK_MESSAGE_IDS.LOG_REQUEST_END]: 2,
  [MAVLINK_MESSAGE_IDS.MAG_CAL_PROGRESS]: 27,
  [MAVLINK_MESSAGE_IDS.MAG_CAL_REPORT]: 44,
  [MAVLINK_MESSAGE_IDS.UAVCAN_NODE_STATUS]: 17,
  [MAVLINK_MESSAGE_IDS.UAVCAN_NODE_INFO]: 116,
  [MAVLINK_MESSAGE_IDS.SETUP_SIGNING]: 42
}

export const MAVLINK_PROTOCOL_VERSION = 3

export const MAV_AUTOPILOT = {
  ARDUPILOTMEGA: 3,
  INVALID: 8
} as const

export const MAV_TYPE = {
  GENERIC: 0,
  FIXED_WING: 1,
  QUADROTOR: 2,
  // Coaxial helicopter — an ArduCopter airframe class.
  COAXIAL: 3,
  HELICOPTER: 4,
  // Antenna tracker — ANTENNA_TRACKER firmware (common.xml). Not yet
  // wired into vehicle classification.
  ANTENNA_TRACKER: 5,
  // Ground control station — the configurator's own type in the outbound
  // GCS HEARTBEAT broadcast (minimal.xml MAV_TYPE_GCS = 6). Never expected
  // inbound from an FC.
  GCS: 6,
  // Airship — ArduBlimp firmware. Not yet wired into classification.
  AIRSHIP: 7,
  // ArduRover reports GROUND_ROVER (land) or SURFACE_BOAT (water);
  // ArduSub reports SUBMARINE.
  GROUND_ROVER: 10,
  SURFACE_BOAT: 11,
  SUBMARINE: 12,
  HEXAROTOR: 13,
  OCTOROTOR: 14,
  TRICOPTER: 15,
  // VTOL / QuadPlane family. ArduPlane's HEARTBEAT.type comes solely from
  // the user-settable Q_MAV_TYPE parameter (QuadPlane::get_mav_type(),
  // ArduPlane/quadplane.cpp): FIXED_WING when Q_MAV_TYPE=0 (the default),
  // else the raw value — not auto-derived from the airframe.
  VTOL_TAILSITTER_DUOROTOR: 19,
  VTOL_TAILSITTER_QUADROTOR: 20,
  VTOL_TILTROTOR: 21,
  VTOL_FIXEDROTOR: 22,
  VTOL_TAILSITTER: 23,
  VTOL_TILTWING: 24,
  VTOL_RESERVED5: 25,
  // 12-rotor — an ArduCopter airframe class.
  DODECAROTOR: 29,
  // 10-rotor — an ArduCopter airframe class.
  DECAROTOR: 35
} as const

export const MAV_MODE_FLAG = {
  CUSTOM_MODE_ENABLED: 1,
  SAFETY_ARMED: 128
} as const

// MAV_STATE — system health enum from HEARTBEAT.system_status
// (full enum per MAVLink common.xml).
export const MAV_STATE = {
  UNINIT: 0,
  BOOT: 1,
  CALIBRATING: 2,
  STANDBY: 3,
  ACTIVE: 4,
  CRITICAL: 5,
  EMERGENCY: 6,
  POWEROFF: 7,
  FLIGHT_TERMINATION: 8
} as const

export const MAV_SEVERITY = {
  EMERGENCY: 0,
  ALERT: 1,
  CRITICAL: 2,
  ERROR: 3,
  WARNING: 4,
  NOTICE: 5,
  INFO: 6,
  DEBUG: 7
} as const

export const MAV_PARAM_TYPE = {
  UINT8: 1,
  INT8: 2,
  UINT16: 3,
  INT16: 4,
  UINT32: 5,
  INT32: 6,
  UINT64: 7,
  INT64: 8,
  REAL32: 9,
  REAL64: 10
} as const

export const MAV_CMD = {
  DO_SET_MODE: 176,
  DO_MOTOR_TEST: 209,
  PREFLIGHT_CALIBRATION: 241,
  PREFLIGHT_STORAGE: 245,
  PREFLIGHT_REBOOT_SHUTDOWN: 246,
  SET_MESSAGE_INTERVAL: 511,
  REQUEST_MESSAGE: 512,
  REQUEST_AUTOPILOT_CAPABILITIES: 520,
  DO_START_MAG_CAL: 42424,
  DO_ACCEPT_MAG_CAL: 42425,
  DO_CANCEL_MAG_CAL: 42426,
  ACCELCAL_VEHICLE_POS: 42429,
  // Ask the autopilot to forward raw CAN frames from a specific bus
  // (1 or 2) via CAN_FRAME (msgid 386) MAVLink messages. param1 = bus,
  // 0 to disable. MAVLink stays alive on the same channel; this is the
  // mechanism Mission Planner uses for its DroneCAN inspector.
  CAN_FORWARD: 32000,
  // Asks the autopilot's MAVLink-UAVCAN bridge to re-emit UAVCAN_NODE_INFO
  // for every currently-online DroneCAN node. Per the MAVLink common-dialect
  // notes the command is "superseded" by MAV_CMD_REQUEST_MESSAGE, but is
  // still the documented broadcast trigger and remains supported on every
  // ArduPilot release that ships AP_DroneCAN today.
  UAVCAN_GET_NODE_INFO: 5200
} as const

export const MAV_PROTOCOL_CAPABILITY = {
  // MAV_PROTOCOL_CAPABILITY_FTP = 32 (bit 5) in common.xml. Note bit 128
  // is SET_POSITION_TARGET_LOCAL_NED, which a copter also advertises;
  // using 128 here would read as MAVFTP-supported on copters but fail on a
  // fixed-wing Plane (which does not set bit 128) despite its FTP support.
  FTP: 32n
} as const

export const MAV_FTP_OPCODE = {
  NONE: 0,
  TERMINATE_SESSION: 1,
  RESET_SESSIONS: 2,
  LIST_DIRECTORY: 3,
  OPEN_FILE_RO: 4,
  READ_FILE: 5,
  CREATE_FILE: 6,
  WRITE_FILE: 7,
  REMOVE_FILE: 8,
  CREATE_DIRECTORY: 9,
  REMOVE_DIRECTORY: 10,
  OPEN_FILE_WO: 11,
  TRUNCATE_FILE: 12,
  RENAME: 13,
  CALC_FILE_CRC32: 14,
  BURST_READ_FILE: 15,
  ACK: 128,
  NAK: 129
} as const

export const MAV_FTP_ERR = {
  NONE: 0,
  FAIL: 1,
  FAIL_ERRNO: 2,
  INVALID_DATA_SIZE: 3,
  INVALID_SESSION: 4,
  NO_SESSIONS_AVAILABLE: 5,
  EOF: 6,
  UNKNOWN_COMMAND: 7,
  FILE_EXISTS: 8,
  FILE_PROTECTED: 9,
  FILE_NOT_FOUND: 10
} as const

export const MOTOR_TEST_THROTTLE_TYPE = {
  PERCENT: 0,
  PWM: 1,
  PILOT: 2,
  CAL: 3
} as const

export const MOTOR_TEST_ORDER = {
  DEFAULT: 0,
  SEQUENCE: 1,
  BOARD: 2
} as const

export const MAV_RESULT = {
  ACCEPTED: 0,
  TEMPORARILY_REJECTED: 1,
  DENIED: 2,
  UNSUPPORTED: 3,
  FAILED: 4,
  IN_PROGRESS: 5
} as const
