# Configuration for the ArduConfigurator wiki.
#
# Built with Sphinx + the Furo theme — a clean, modern, responsive docs theme
# (light/dark mode toggle, collapsible mobile nav, Note/Warning/Tip callouts,
# prev/next, and Edit-this-page links) served under arduconfigurator.com/wiki.

project = 'ArduConfigurator'
author = 'ArduConfigurator contributors'

extensions = [
    'sphinx.ext.todo',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'venv', '.venv']

# -- HTML output -------------------------------------------------------------
html_theme = 'furo'
html_theme_options = {
    # "Edit this page" links back to wiki/ on GitHub — Furo's built-in mechanism,
    # replacing the RTD html_context github_* config.
    'source_repository': 'https://github.com/j-w9/arduconfigurator/',
    'source_branch': 'main',
    'source_directory': 'wiki/',
}
html_title = 'ArduConfigurator Wiki'
html_show_copyright = False
html_static_path = ['_static']
html_css_files = ['custom.css']
# Loaded as an external file rather than an inline <script>: the wiki is served
# from the same origin as the app, so the app's CSP (script-src 'self') applies
# here and blocks inline execution. The script early-returns on pages without
# the search elements.
html_js_files = ['parameter-search.js']

# Served under arduconfigurator.com/wiki. Sphinx emits relative asset/link URLs,
# so the build works unchanged under that subpath; html_baseurl only sets the
# canonical URL used in <link rel="canonical"> and the sitemap.
html_baseurl = 'https://arduconfigurator.com/wiki/'

todo_include_todos = True


# -- The :param:`NAME` role --------------------------------------------------
#
# Prose about a parameter should LINK to the generated reference rather than
# restate the firmware's own description — restated descriptions rot silently
# across firmware releases, a link does not.
#
# `:param:`RSSI_TYPE`` renders as a literal that links to that parameter's entry
# in the generated reference. The target is resolved at BUILD time out of
# _static/parameter-index.json (the same index the app's "i" bubbles search), so
# a mistyped or non-existent parameter name is a build warning rather than a
# dead link an operator finds later. Names that resolve get the direct
# `parameters/group-<g>.html#param-<name>` deep link; anything unresolved falls
# back to the app's own `parameters/index.html?param=<NAME>` entry point.
#
# The index only carries the reference's firmware (ArduCopter 4.7), so a
# parameter that only exists on older firmware — ARMING_CHECK, say — has no
# entry and should be written as a plain ``literal`` with the prose saying so.

import json
import pathlib

from docutils import nodes

_PARAM_INDEX_PATH = pathlib.Path(__file__).parent / '_static' / 'parameter-index.json'


def _load_parameter_index():
    try:
        payload = json.loads(_PARAM_INDEX_PATH.read_text())
    except (OSError, ValueError):
        # The index is generated by wiki/tools/generate_parameter_reference.py.
        # Without it every :param: falls back to the ?param= entry point, which
        # still works — so a bare `sphinx-build` stays usable.
        return {}
    return {entry['n']: entry.get('g', '') for entry in payload.get('params', [])}


_PARAMETER_INDEX = _load_parameter_index()


def _parameter_role(name, rawtext, text, lineno, inliner, options=None, content=None):
    param = text.strip()
    document = inliner.document
    # Depth of the referring page, so the link works from wiki/foo.rst and from
    # wiki/first-time-setup/foo.rst alike.
    docname = document.settings.env.docname
    prefix = '../' * docname.count('/')

    group = _PARAMETER_INDEX.get(param)
    messages = []
    if group:
        anchor = param.lower().replace('_', '-')
        uri = '{}parameters/group-{}.html#param-{}'.format(prefix, group, anchor)
    else:
        uri = '{}parameters/index.html?param={}'.format(prefix, param)
        if _PARAMETER_INDEX:
            messages.append(inliner.reporter.warning(
                '{} is not in the generated parameter reference — check the '
                'spelling, or write it as a plain ``literal`` if it only exists '
                'on other firmware.'.format(param),
                line=lineno,
            ))

    reference = nodes.reference('', '', internal=False, refuri=uri, classes=['param-ref'])
    reference += nodes.literal(rawtext, param, classes=['xref'])
    return [reference], messages


def setup(app):
    app.add_role('param', _parameter_role)
    return {'parallel_read_safe': True, 'parallel_write_safe': True}
