// GENERATED by packages/param-metadata/scripts/generate-board-rotations.mjs
// from ArduPilot AP_Math/vector3.cpp + rotations.h — do NOT edit by hand.
// Regenerate: ARDUPILOT_REPO_PATH=/path/to/ardupilot node packages/param-metadata/scripts/generate-board-rotations.mjs

/** One AHRS_ORIENTATION value and the rotation it applies. */
export interface BoardRotation {
  /** The AHRS_ORIENTATION parameter value. */
  value: number
  /** ArduPilot's own enum name, e.g. ROTATION_YAW_270. */
  name: string
  /** Row-major 3x3. Column j is the image of basis vector j, matching
   *  Vector3::rotate() — so rotated = matrix * original. */
  matrix: readonly (readonly number[])[]
}

/** Every fixed rotation AHRS_ORIENTATION accepts. Custom (100/101/102) are
 *  excluded: they are whatever the operator put in CUST_ROT*, not a fixed
 *  value anything can be matched against. */
export const BOARD_ROTATIONS: readonly BoardRotation[] = [
  {
    "value": 0,
    "name": "ROTATION_NONE",
    "matrix": [
      [
        1,
        0,
        0
      ],
      [
        0,
        1,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "value": 1,
    "name": "ROTATION_YAW_45",
    "matrix": [
      [
        0.707106781187,
        -0.707106781187,
        0
      ],
      [
        0.707106781187,
        0.707106781187,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "value": 2,
    "name": "ROTATION_YAW_90",
    "matrix": [
      [
        0,
        -1,
        0
      ],
      [
        1,
        0,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "value": 3,
    "name": "ROTATION_YAW_135",
    "matrix": [
      [
        -0.707106781187,
        -0.707106781187,
        0
      ],
      [
        0.707106781187,
        -0.707106781187,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "value": 4,
    "name": "ROTATION_YAW_180",
    "matrix": [
      [
        -1,
        0,
        0
      ],
      [
        0,
        -1,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "value": 5,
    "name": "ROTATION_YAW_225",
    "matrix": [
      [
        -0.707106781187,
        0.707106781187,
        0
      ],
      [
        -0.707106781187,
        -0.707106781187,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "value": 6,
    "name": "ROTATION_YAW_270",
    "matrix": [
      [
        0,
        1,
        0
      ],
      [
        -1,
        0,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "value": 7,
    "name": "ROTATION_YAW_315",
    "matrix": [
      [
        0.707106781187,
        0.707106781187,
        0
      ],
      [
        -0.707106781187,
        0.707106781187,
        0
      ],
      [
        0,
        0,
        1
      ]
    ]
  },
  {
    "value": 8,
    "name": "ROTATION_ROLL_180",
    "matrix": [
      [
        1,
        0,
        0
      ],
      [
        0,
        -1,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "value": 9,
    "name": "ROTATION_ROLL_180_YAW_45",
    "matrix": [
      [
        0.707106781187,
        0.707106781187,
        0
      ],
      [
        0.707106781187,
        -0.707106781187,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "value": 10,
    "name": "ROTATION_ROLL_180_YAW_90",
    "matrix": [
      [
        0,
        1,
        0
      ],
      [
        1,
        0,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "value": 11,
    "name": "ROTATION_ROLL_180_YAW_135",
    "matrix": [
      [
        -0.707106781187,
        0.707106781187,
        0
      ],
      [
        0.707106781187,
        0.707106781187,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "value": 12,
    "name": "ROTATION_PITCH_180",
    "matrix": [
      [
        -1,
        0,
        0
      ],
      [
        0,
        1,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "value": 13,
    "name": "ROTATION_ROLL_180_YAW_225",
    "matrix": [
      [
        -0.707106781187,
        -0.707106781187,
        0
      ],
      [
        -0.707106781187,
        0.707106781187,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "value": 14,
    "name": "ROTATION_ROLL_180_YAW_270",
    "matrix": [
      [
        0,
        -1,
        0
      ],
      [
        -1,
        0,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "value": 15,
    "name": "ROTATION_ROLL_180_YAW_315",
    "matrix": [
      [
        0.707106781187,
        -0.707106781187,
        0
      ],
      [
        -0.707106781187,
        -0.707106781187,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "value": 16,
    "name": "ROTATION_ROLL_90",
    "matrix": [
      [
        1,
        0,
        0
      ],
      [
        0,
        0,
        -1
      ],
      [
        0,
        1,
        0
      ]
    ]
  },
  {
    "value": 17,
    "name": "ROTATION_ROLL_90_YAW_45",
    "matrix": [
      [
        0.707106781187,
        0,
        0.707106781187
      ],
      [
        0.707106781187,
        0,
        -0.707106781187
      ],
      [
        0,
        1,
        0
      ]
    ]
  },
  {
    "value": 18,
    "name": "ROTATION_ROLL_90_YAW_90",
    "matrix": [
      [
        0,
        0,
        1
      ],
      [
        1,
        0,
        0
      ],
      [
        0,
        1,
        0
      ]
    ]
  },
  {
    "value": 19,
    "name": "ROTATION_ROLL_90_YAW_135",
    "matrix": [
      [
        -0.707106781187,
        0,
        0.707106781187
      ],
      [
        0.707106781187,
        0,
        0.707106781187
      ],
      [
        0,
        1,
        0
      ]
    ]
  },
  {
    "value": 20,
    "name": "ROTATION_ROLL_270",
    "matrix": [
      [
        1,
        0,
        0
      ],
      [
        0,
        0,
        1
      ],
      [
        0,
        -1,
        0
      ]
    ]
  },
  {
    "value": 21,
    "name": "ROTATION_ROLL_270_YAW_45",
    "matrix": [
      [
        0.707106781187,
        0,
        -0.707106781187
      ],
      [
        0.707106781187,
        0,
        0.707106781187
      ],
      [
        0,
        -1,
        0
      ]
    ]
  },
  {
    "value": 22,
    "name": "ROTATION_ROLL_270_YAW_90",
    "matrix": [
      [
        0,
        0,
        -1
      ],
      [
        1,
        0,
        0
      ],
      [
        0,
        -1,
        0
      ]
    ]
  },
  {
    "value": 23,
    "name": "ROTATION_ROLL_270_YAW_135",
    "matrix": [
      [
        -0.707106781187,
        0,
        -0.707106781187
      ],
      [
        0.707106781187,
        0,
        -0.707106781187
      ],
      [
        0,
        -1,
        0
      ]
    ]
  },
  {
    "value": 24,
    "name": "ROTATION_PITCH_90",
    "matrix": [
      [
        0,
        0,
        1
      ],
      [
        0,
        1,
        0
      ],
      [
        -1,
        0,
        0
      ]
    ]
  },
  {
    "value": 25,
    "name": "ROTATION_PITCH_270",
    "matrix": [
      [
        0,
        0,
        -1
      ],
      [
        0,
        1,
        0
      ],
      [
        1,
        0,
        0
      ]
    ]
  },
  {
    "value": 26,
    "name": "ROTATION_PITCH_180_YAW_90",
    "matrix": [
      [
        0,
        -1,
        0
      ],
      [
        -1,
        0,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "value": 27,
    "name": "ROTATION_PITCH_180_YAW_270",
    "matrix": [
      [
        0,
        1,
        0
      ],
      [
        1,
        0,
        0
      ],
      [
        0,
        0,
        -1
      ]
    ]
  },
  {
    "value": 28,
    "name": "ROTATION_ROLL_90_PITCH_90",
    "matrix": [
      [
        0,
        1,
        0
      ],
      [
        0,
        0,
        -1
      ],
      [
        -1,
        0,
        0
      ]
    ]
  },
  {
    "value": 29,
    "name": "ROTATION_ROLL_180_PITCH_90",
    "matrix": [
      [
        0,
        0,
        -1
      ],
      [
        0,
        -1,
        0
      ],
      [
        -1,
        0,
        0
      ]
    ]
  },
  {
    "value": 30,
    "name": "ROTATION_ROLL_270_PITCH_90",
    "matrix": [
      [
        0,
        -1,
        0
      ],
      [
        0,
        0,
        1
      ],
      [
        -1,
        0,
        0
      ]
    ]
  },
  {
    "value": 31,
    "name": "ROTATION_ROLL_90_PITCH_180",
    "matrix": [
      [
        -1,
        0,
        0
      ],
      [
        0,
        0,
        -1
      ],
      [
        0,
        -1,
        0
      ]
    ]
  },
  {
    "value": 32,
    "name": "ROTATION_ROLL_270_PITCH_180",
    "matrix": [
      [
        -1,
        0,
        0
      ],
      [
        0,
        0,
        1
      ],
      [
        0,
        1,
        0
      ]
    ]
  },
  {
    "value": 33,
    "name": "ROTATION_ROLL_90_PITCH_270",
    "matrix": [
      [
        0,
        -1,
        0
      ],
      [
        0,
        0,
        -1
      ],
      [
        1,
        0,
        0
      ]
    ]
  },
  {
    "value": 34,
    "name": "ROTATION_ROLL_180_PITCH_270",
    "matrix": [
      [
        0,
        0,
        1
      ],
      [
        0,
        -1,
        0
      ],
      [
        1,
        0,
        0
      ]
    ]
  },
  {
    "value": 35,
    "name": "ROTATION_ROLL_270_PITCH_270",
    "matrix": [
      [
        0,
        1,
        0
      ],
      [
        0,
        0,
        1
      ],
      [
        1,
        0,
        0
      ]
    ]
  },
  {
    "value": 36,
    "name": "ROTATION_ROLL_90_PITCH_180_YAW_90",
    "matrix": [
      [
        0,
        0,
        1
      ],
      [
        -1,
        0,
        0
      ],
      [
        0,
        -1,
        0
      ]
    ]
  },
  {
    "value": 37,
    "name": "ROTATION_ROLL_90_YAW_270",
    "matrix": [
      [
        0,
        0,
        -1
      ],
      [
        -1,
        0,
        0
      ],
      [
        0,
        1,
        0
      ]
    ]
  },
  {
    "value": 38,
    "name": "ROTATION_ROLL_90_PITCH_68_YAW_293",
    "matrix": [
      [
        0.143038972312,
        0.368776486503,
        -0.918446381343
      ],
      [
        -0.332132777797,
        -0.856289421466,
        -0.395545502563
      ],
      [
        -0.932323801216,
        0.361624570082,
        0
      ]
    ]
  },
  {
    "value": 39,
    "name": "ROTATION_PITCH_315",
    "matrix": [
      [
        0.707106781187,
        0,
        -0.707106781187
      ],
      [
        0,
        1,
        0
      ],
      [
        0.707106781187,
        0,
        0.707106781187
      ]
    ]
  },
  {
    "value": 40,
    "name": "ROTATION_ROLL_90_PITCH_315",
    "matrix": [
      [
        0.707106781187,
        -0.707106781187,
        0
      ],
      [
        0,
        0,
        -1
      ],
      [
        0.707106781187,
        0.707106781187,
        0
      ]
    ]
  },
  {
    "value": 41,
    "name": "ROTATION_PITCH_7",
    "matrix": [
      [
        0.992546151641,
        0,
        0.121869343405
      ],
      [
        0,
        1,
        0
      ],
      [
        -0.121869343405,
        0,
        0.992546151641
      ]
    ]
  },
  {
    "value": 42,
    "name": "ROTATION_ROLL_45",
    "matrix": [
      [
        1,
        0,
        0
      ],
      [
        0,
        0.707106781187,
        -0.707106781187
      ],
      [
        0,
        0.707106781187,
        0.707106781187
      ]
    ]
  },
  {
    "value": 43,
    "name": "ROTATION_ROLL_315",
    "matrix": [
      [
        1,
        0,
        0
      ],
      [
        0,
        0.707106781187,
        0.707106781187
      ],
      [
        0,
        -0.707106781187,
        0.707106781187
      ]
    ]
  }
]
