// GENERATED by packages/param-metadata/scripts/generate-frame-motor-layouts.mjs
// from ArduPilot AP_MotorsMatrix.cpp — do NOT edit by hand.
// Regenerate: ARDUPILOT_REPO_PATH=/path/to/ardupilot node packages/param-metadata/scripts/generate-frame-motor-layouts.mjs

/** One motor in a frame's top-down layout. x is right, y is down, unit-ish. */
export interface FrameMotorNode {
  /** 1-based position in ArduPilot's add order (= the MOTn output). */
  motorNumber: number
  x: number
  y: number
  /** Prop rotation seen from above; 'none' for yaw-neutral (NYT) motors. */
  spin: 'cw' | 'ccw' | 'none'
  /** Present on coaxial frames (Y6, X8): which motor of the shared arm. */
  stack?: 'top' | 'bottom'
}

/** FRAME_CLASS value -> FRAME_TYPE value -> motor layout. */
export const FRAME_MOTOR_LAYOUTS: Record<number, Record<number, readonly FrameMotorNode[]>> =
{
  "1": {
    "0": [
      {
        "motorNumber": 1,
        "x": 0.74,
        "y": 0,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": -0.74,
        "y": 0,
        "spin": "ccw"
      },
      {
        "motorNumber": 3,
        "x": 0,
        "y": -0.74,
        "spin": "cw"
      },
      {
        "motorNumber": 4,
        "x": 0,
        "y": 0.74,
        "spin": "cw"
      }
    ],
    "1": [
      {
        "motorNumber": 1,
        "x": 0.523,
        "y": -0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": -0.523,
        "y": 0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 3,
        "x": -0.523,
        "y": -0.523,
        "spin": "cw"
      },
      {
        "motorNumber": 4,
        "x": 0.523,
        "y": 0.523,
        "spin": "cw"
      }
    ],
    "2": [
      {
        "motorNumber": 1,
        "x": 0.523,
        "y": -0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": -0.523,
        "y": 0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 3,
        "x": -0.523,
        "y": -0.523,
        "spin": "cw"
      },
      {
        "motorNumber": 4,
        "x": 0.523,
        "y": 0.523,
        "spin": "cw"
      }
    ],
    "3": [
      {
        "motorNumber": 1,
        "x": 0.523,
        "y": -0.523,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": -0.523,
        "y": 0.523,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": -0.523,
        "y": -0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0.523,
        "y": 0.523,
        "spin": "ccw"
      }
    ],
    "4": [
      {
        "motorNumber": 1,
        "x": 0.675,
        "y": -0.39,
        "spin": "none"
      },
      {
        "motorNumber": 2,
        "x": 0,
        "y": 0.733,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": -0.675,
        "y": -0.39,
        "spin": "none"
      },
      {
        "motorNumber": 4,
        "x": 0,
        "y": 0.733,
        "spin": "ccw",
        "stack": "bottom"
      }
    ],
    "5": [
      {
        "motorNumber": 1,
        "x": 0.675,
        "y": -0.39,
        "spin": "none"
      },
      {
        "motorNumber": 2,
        "x": 0,
        "y": 0.733,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": -0.675,
        "y": -0.39,
        "spin": "none"
      },
      {
        "motorNumber": 4,
        "x": 0,
        "y": 0.733,
        "spin": "cw",
        "stack": "bottom"
      }
    ],
    "6": [
      {
        "motorNumber": 1,
        "x": 0.74,
        "y": 0,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": -0.74,
        "y": 0,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": 0,
        "y": -0.74,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0,
        "y": 0.74,
        "spin": "ccw"
      }
    ],
    "12": [
      {
        "motorNumber": 1,
        "x": 0.523,
        "y": 0.523,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": 0.523,
        "y": -0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 3,
        "x": -0.523,
        "y": 0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": -0.523,
        "y": -0.523,
        "spin": "cw"
      }
    ],
    "13": [
      {
        "motorNumber": 1,
        "x": 0.523,
        "y": -0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": -0.523,
        "y": -0.523,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": -0.523,
        "y": 0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0.523,
        "y": 0.523,
        "spin": "cw"
      }
    ],
    "14": [
      {
        "motorNumber": 1,
        "x": 0.523,
        "y": -0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": 0.523,
        "y": 0.523,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": -0.523,
        "y": 0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": -0.523,
        "y": -0.523,
        "spin": "cw"
      }
    ],
    "16": [
      {
        "motorNumber": 1,
        "x": 0.74,
        "y": 0,
        "spin": "none"
      },
      {
        "motorNumber": 2,
        "x": -0.74,
        "y": 0,
        "spin": "none"
      },
      {
        "motorNumber": 3,
        "x": 0,
        "y": -0.74,
        "spin": "none"
      },
      {
        "motorNumber": 4,
        "x": 0,
        "y": 0.74,
        "spin": "none"
      }
    ],
    "17": [
      {
        "motorNumber": 1,
        "x": 0.523,
        "y": -0.523,
        "spin": "none"
      },
      {
        "motorNumber": 2,
        "x": -0.523,
        "y": 0.523,
        "spin": "none"
      },
      {
        "motorNumber": 3,
        "x": -0.523,
        "y": -0.523,
        "spin": "none"
      },
      {
        "motorNumber": 4,
        "x": 0.523,
        "y": 0.523,
        "spin": "none"
      }
    ],
    "18": [
      {
        "motorNumber": 1,
        "x": 0.523,
        "y": 0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": 0.523,
        "y": -0.523,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": -0.523,
        "y": 0.523,
        "spin": "cw"
      },
      {
        "motorNumber": 4,
        "x": -0.523,
        "y": -0.523,
        "spin": "ccw"
      }
    ],
    "19": [
      {
        "motorNumber": 1,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": 0,
        "y": 0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": 0,
        "y": 0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 4,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw"
      }
    ]
  },
  "2": {
    "0": [
      {
        "motorNumber": 1,
        "x": 0,
        "y": -0.74,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": 0,
        "y": 0.74,
        "spin": "ccw"
      },
      {
        "motorNumber": 3,
        "x": -0.641,
        "y": 0.37,
        "spin": "cw"
      },
      {
        "motorNumber": 4,
        "x": 0.641,
        "y": -0.37,
        "spin": "ccw"
      },
      {
        "motorNumber": 5,
        "x": -0.641,
        "y": -0.37,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": 0.641,
        "y": 0.37,
        "spin": "cw"
      }
    ],
    "1": [
      {
        "motorNumber": 1,
        "x": 0.74,
        "y": 0,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": -0.74,
        "y": 0,
        "spin": "ccw"
      },
      {
        "motorNumber": 3,
        "x": -0.37,
        "y": -0.641,
        "spin": "cw"
      },
      {
        "motorNumber": 4,
        "x": 0.37,
        "y": 0.641,
        "spin": "ccw"
      },
      {
        "motorNumber": 5,
        "x": 0.37,
        "y": -0.641,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": -0.37,
        "y": 0.641,
        "spin": "cw"
      }
    ],
    "3": [
      {
        "motorNumber": 1,
        "x": 0.74,
        "y": 0,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": -0.74,
        "y": 0,
        "spin": "ccw"
      },
      {
        "motorNumber": 3,
        "x": -0.523,
        "y": -0.523,
        "spin": "cw"
      },
      {
        "motorNumber": 4,
        "x": 0.523,
        "y": 0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 5,
        "x": 0.523,
        "y": -0.523,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": -0.523,
        "y": 0.523,
        "spin": "cw"
      }
    ],
    "13": [
      {
        "motorNumber": 1,
        "x": 0.37,
        "y": -0.641,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": -0.37,
        "y": -0.641,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": -0.74,
        "y": 0,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": -0.37,
        "y": 0.641,
        "spin": "cw"
      },
      {
        "motorNumber": 5,
        "x": 0.37,
        "y": 0.641,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": 0.74,
        "y": 0,
        "spin": "cw"
      }
    ],
    "14": [
      {
        "motorNumber": 1,
        "x": 0.37,
        "y": -0.641,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": 0.74,
        "y": 0,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": 0.37,
        "y": 0.641,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": -0.37,
        "y": 0.641,
        "spin": "cw"
      },
      {
        "motorNumber": 5,
        "x": -0.74,
        "y": 0,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": -0.37,
        "y": -0.641,
        "spin": "cw"
      }
    ]
  },
  "3": {
    "0": [
      {
        "motorNumber": 1,
        "x": 0,
        "y": -0.8,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": 0,
        "y": 0.8,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": 0.566,
        "y": -0.566,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0.566,
        "y": 0.566,
        "spin": "ccw"
      },
      {
        "motorNumber": 5,
        "x": -0.566,
        "y": -0.566,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": -0.566,
        "y": 0.566,
        "spin": "ccw"
      },
      {
        "motorNumber": 7,
        "x": -0.8,
        "y": 0,
        "spin": "cw"
      },
      {
        "motorNumber": 8,
        "x": 0.8,
        "y": 0,
        "spin": "cw"
      }
    ],
    "1": [
      {
        "motorNumber": 1,
        "x": 0.306,
        "y": -0.739,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": -0.306,
        "y": 0.739,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": 0.739,
        "y": -0.306,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0.306,
        "y": 0.739,
        "spin": "ccw"
      },
      {
        "motorNumber": 5,
        "x": -0.306,
        "y": -0.739,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": -0.739,
        "y": 0.306,
        "spin": "ccw"
      },
      {
        "motorNumber": 7,
        "x": -0.739,
        "y": -0.306,
        "spin": "cw"
      },
      {
        "motorNumber": 8,
        "x": 0.739,
        "y": 0.306,
        "spin": "cw"
      }
    ],
    "2": [
      {
        "motorNumber": 1,
        "x": -0.74,
        "y": -0.303,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": 0.722,
        "y": 0.345,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": -0.722,
        "y": 0.345,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0.358,
        "y": 0.716,
        "spin": "ccw"
      },
      {
        "motorNumber": 5,
        "x": -0.566,
        "y": -0.566,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": 0.74,
        "y": -0.303,
        "spin": "ccw"
      },
      {
        "motorNumber": 7,
        "x": 0.566,
        "y": -0.566,
        "spin": "cw"
      },
      {
        "motorNumber": 8,
        "x": -0.358,
        "y": 0.716,
        "spin": "cw"
      }
    ],
    "3": [
      {
        "motorNumber": 1,
        "x": 0.566,
        "y": -0.566,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": -0.566,
        "y": 0.566,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": 0.759,
        "y": -0.253,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0.566,
        "y": 0.566,
        "spin": "ccw"
      },
      {
        "motorNumber": 5,
        "x": -0.566,
        "y": -0.566,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": -0.759,
        "y": 0.253,
        "spin": "ccw"
      },
      {
        "motorNumber": 7,
        "x": -0.759,
        "y": -0.253,
        "spin": "cw"
      },
      {
        "motorNumber": 8,
        "x": 0.759,
        "y": 0.253,
        "spin": "cw"
      }
    ],
    "13": [
      {
        "motorNumber": 1,
        "x": 0.306,
        "y": -0.739,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": -0.306,
        "y": -0.739,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": -0.739,
        "y": -0.306,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": -0.739,
        "y": 0.306,
        "spin": "cw"
      },
      {
        "motorNumber": 5,
        "x": -0.306,
        "y": 0.739,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": 0.306,
        "y": 0.739,
        "spin": "cw"
      },
      {
        "motorNumber": 7,
        "x": 0.739,
        "y": 0.306,
        "spin": "ccw"
      },
      {
        "motorNumber": 8,
        "x": 0.739,
        "y": -0.306,
        "spin": "cw"
      }
    ],
    "14": [
      {
        "motorNumber": 1,
        "x": 0.306,
        "y": -0.739,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": 0.739,
        "y": -0.306,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": 0.739,
        "y": 0.306,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0.306,
        "y": 0.739,
        "spin": "cw"
      },
      {
        "motorNumber": 5,
        "x": -0.306,
        "y": 0.739,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": -0.739,
        "y": 0.306,
        "spin": "cw"
      },
      {
        "motorNumber": 7,
        "x": -0.739,
        "y": -0.306,
        "spin": "ccw"
      },
      {
        "motorNumber": 8,
        "x": -0.306,
        "y": -0.739,
        "spin": "cw"
      }
    ],
    "15": [
      {
        "motorNumber": 1,
        "x": -0.253,
        "y": 0.759,
        "spin": "cw"
      },
      {
        "motorNumber": 2,
        "x": 0.253,
        "y": -0.759,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": -0.566,
        "y": 0.566,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": -0.253,
        "y": -0.759,
        "spin": "ccw"
      },
      {
        "motorNumber": 5,
        "x": 0.253,
        "y": 0.759,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": 0.566,
        "y": -0.566,
        "spin": "ccw"
      },
      {
        "motorNumber": 7,
        "x": 0.566,
        "y": 0.566,
        "spin": "cw"
      },
      {
        "motorNumber": 8,
        "x": -0.566,
        "y": -0.566,
        "spin": "cw"
      }
    ]
  },
  "4": {
    "0": [
      {
        "motorNumber": 1,
        "x": 0,
        "y": -0.78,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": -0.78,
        "y": 0,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": 0,
        "y": 0.78,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0.78,
        "y": 0,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 5,
        "x": -0.78,
        "y": 0,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 6,
        "x": 0,
        "y": -0.78,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": 0.78,
        "y": 0,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 8,
        "x": 0,
        "y": 0.78,
        "spin": "cw",
        "stack": "bottom"
      }
    ],
    "1": [
      {
        "motorNumber": 1,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": -0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 5,
        "x": -0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 6,
        "x": 0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": 0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 8,
        "x": -0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "bottom"
      }
    ],
    "2": [
      {
        "motorNumber": 1,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": -0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 5,
        "x": -0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 6,
        "x": 0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": 0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 8,
        "x": -0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "bottom"
      }
    ],
    "3": [
      {
        "motorNumber": 1,
        "x": 0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": -0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": -0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 5,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 6,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": 0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 8,
        "x": -0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "bottom"
      }
    ],
    "12": [
      {
        "motorNumber": 1,
        "x": 0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": -0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 5,
        "x": 0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 6,
        "x": 0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": -0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 8,
        "x": -0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "bottom"
      }
    ],
    "14": [
      {
        "motorNumber": 1,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": 0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 3,
        "x": 0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 5,
        "x": -0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 6,
        "x": -0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 8,
        "x": -0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "bottom"
      }
    ],
    "18": [
      {
        "motorNumber": 1,
        "x": 0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": 0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": -0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": -0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 5,
        "x": 0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 6,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": -0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 8,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "bottom"
      }
    ],
    "20": [
      {
        "motorNumber": 1,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": -0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 5,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 6,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": 0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 8,
        "x": -0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "bottom"
      }
    ],
    "21": [
      {
        "motorNumber": 1,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": 0.552,
        "y": -0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 3,
        "x": 0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0.552,
        "y": 0.552,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 5,
        "x": -0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 6,
        "x": -0.552,
        "y": 0.552,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 8,
        "x": -0.552,
        "y": -0.552,
        "spin": "cw",
        "stack": "bottom"
      }
    ]
  },
  "5": {
    "10": [
      {
        "motorNumber": 1,
        "x": 0.698,
        "y": -0.349,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": 0.698,
        "y": -0.349,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 3,
        "x": 0,
        "y": 0.698,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0,
        "y": 0.698,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 5,
        "x": -0.698,
        "y": -0.349,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 6,
        "x": -0.698,
        "y": -0.349,
        "spin": "ccw",
        "stack": "bottom"
      }
    ],
    "11": [
      {
        "motorNumber": 1,
        "x": 0,
        "y": 0.698,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": 0.698,
        "y": -0.349,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 3,
        "x": -0.698,
        "y": -0.349,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0,
        "y": 0.698,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 5,
        "x": 0.698,
        "y": -0.349,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 6,
        "x": -0.698,
        "y": -0.349,
        "spin": "cw",
        "stack": "bottom"
      }
    ]
  },
  "12": {
    "0": [
      {
        "motorNumber": 1,
        "x": 0,
        "y": -0.78,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": 0,
        "y": -0.78,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 3,
        "x": 0.675,
        "y": -0.39,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0.675,
        "y": -0.39,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 5,
        "x": 0.675,
        "y": 0.39,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 6,
        "x": 0.675,
        "y": 0.39,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": 0,
        "y": 0.78,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 8,
        "x": 0,
        "y": 0.78,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 9,
        "x": -0.675,
        "y": 0.39,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 10,
        "x": -0.675,
        "y": 0.39,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 11,
        "x": -0.675,
        "y": -0.39,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 12,
        "x": -0.675,
        "y": -0.39,
        "spin": "ccw",
        "stack": "bottom"
      }
    ],
    "1": [
      {
        "motorNumber": 1,
        "x": 0.39,
        "y": -0.675,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 2,
        "x": 0.39,
        "y": -0.675,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 3,
        "x": 0.78,
        "y": 0,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 4,
        "x": 0.78,
        "y": 0,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 5,
        "x": 0.39,
        "y": 0.675,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 6,
        "x": 0.39,
        "y": 0.675,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 7,
        "x": -0.39,
        "y": 0.675,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 8,
        "x": -0.39,
        "y": 0.675,
        "spin": "ccw",
        "stack": "bottom"
      },
      {
        "motorNumber": 9,
        "x": -0.78,
        "y": 0,
        "spin": "ccw",
        "stack": "top"
      },
      {
        "motorNumber": 10,
        "x": -0.78,
        "y": 0,
        "spin": "cw",
        "stack": "bottom"
      },
      {
        "motorNumber": 11,
        "x": -0.39,
        "y": -0.675,
        "spin": "cw",
        "stack": "top"
      },
      {
        "motorNumber": 12,
        "x": -0.39,
        "y": -0.675,
        "spin": "ccw",
        "stack": "bottom"
      }
    ]
  },
  "14": {
    "0": [
      {
        "motorNumber": 1,
        "x": 0,
        "y": -0.8,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": 0.47,
        "y": -0.647,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": 0.761,
        "y": -0.247,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0.761,
        "y": 0.247,
        "spin": "cw"
      },
      {
        "motorNumber": 5,
        "x": 0.47,
        "y": 0.647,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": 0,
        "y": 0.8,
        "spin": "cw"
      },
      {
        "motorNumber": 7,
        "x": -0.47,
        "y": 0.647,
        "spin": "ccw"
      },
      {
        "motorNumber": 8,
        "x": -0.761,
        "y": 0.247,
        "spin": "cw"
      },
      {
        "motorNumber": 9,
        "x": -0.761,
        "y": -0.247,
        "spin": "ccw"
      },
      {
        "motorNumber": 10,
        "x": -0.47,
        "y": -0.647,
        "spin": "cw"
      }
    ],
    "1": [
      {
        "motorNumber": 1,
        "x": 0.247,
        "y": -0.761,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": 0.647,
        "y": -0.47,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": 0.8,
        "y": 0,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0.647,
        "y": 0.47,
        "spin": "cw"
      },
      {
        "motorNumber": 5,
        "x": 0.247,
        "y": 0.761,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": -0.247,
        "y": 0.761,
        "spin": "cw"
      },
      {
        "motorNumber": 7,
        "x": -0.647,
        "y": 0.47,
        "spin": "ccw"
      },
      {
        "motorNumber": 8,
        "x": -0.8,
        "y": 0,
        "spin": "cw"
      },
      {
        "motorNumber": 9,
        "x": -0.647,
        "y": -0.47,
        "spin": "ccw"
      },
      {
        "motorNumber": 10,
        "x": -0.247,
        "y": -0.761,
        "spin": "cw"
      }
    ],
    "14": [
      {
        "motorNumber": 1,
        "x": 0.247,
        "y": -0.761,
        "spin": "ccw"
      },
      {
        "motorNumber": 2,
        "x": 0.647,
        "y": -0.47,
        "spin": "cw"
      },
      {
        "motorNumber": 3,
        "x": 0.8,
        "y": 0,
        "spin": "ccw"
      },
      {
        "motorNumber": 4,
        "x": 0.647,
        "y": 0.47,
        "spin": "cw"
      },
      {
        "motorNumber": 5,
        "x": 0.247,
        "y": 0.761,
        "spin": "ccw"
      },
      {
        "motorNumber": 6,
        "x": -0.247,
        "y": 0.761,
        "spin": "cw"
      },
      {
        "motorNumber": 7,
        "x": -0.647,
        "y": 0.47,
        "spin": "ccw"
      },
      {
        "motorNumber": 8,
        "x": -0.8,
        "y": 0,
        "spin": "cw"
      },
      {
        "motorNumber": 9,
        "x": -0.647,
        "y": -0.47,
        "spin": "ccw"
      },
      {
        "motorNumber": 10,
        "x": -0.247,
        "y": -0.761,
        "spin": "cw"
      }
    ]
  }
}
